---
# Cluster: dk1d-baseline
# Site: dk1d
# Environment: development
# Created: Fri Dec 19 23:20:48 UTC 2025

apiVersion: v1alpha1
kind: Cluster
name: dk1d-baseline
labels:
  site: dk1d
  environment: development
  platform: proxmox
  cluster: baseline
kubernetes:
  version: v1.29.0
talos:
  version: v1.9.5
features:
  enableWorkloadProxy: true
  diskEncryption: false
  useEmbeddedDiscoveryService: true

---
# Control plane machine set
apiVersion: v1alpha1
kind: MachineSet
name: dk1d-baseline-control-planes
cluster: dk1d-baseline
machineClass:
  name: control-plane
  machineCount: 1
  
  # Machine allocation strategy
  allocationStrategy:
    type: static  # Manually assign machines via Omni UI or labels
  
  # Machine requirements
  requirements:
    - key: "site"
      operator: "In"
      values: ["dk1d"]
    - key: "platform"
      operator: "In"
      values: ["proxmox"]

patches:
  - |
    machine:
      install:
        disk: /dev/sda
      kubelet:
        nodeIP:
          validSubnets:
            - 0.0.0.0/0  # Use primary interface IP
        extraArgs:
          rotate-server-certificates: "true"
      network:
        interfaces:
          - interface: eth0
            dhcp: true
      time:
        servers:
          - time.cloudflare.com
          - time.google.com
    cluster:
      controllerManager:
        extraArgs:
          bind-address: "0.0.0.0"
      scheduler:
        extraArgs:
          bind-address: "0.0.0.0"
      apiServer:
        certSANs:
          - dk1d-baseline.local
          - dk1d-baseline.example.com
      proxy:
        disabled: false
      discovery:
        enabled: true
        registries:
          service:
            disabled: false

---
# Worker machine set
apiVersion: v1alpha1
kind: MachineSet
name: dk1d-baseline-workers
cluster: dk1d-baseline
machineClass:
  name: worker
  machineCount: 3
  
  allocationStrategy:
    type: static
  
  requirements:
    - key: "site"
      operator: "In"
      values: ["dk1d"]
    - key: "platform"
      operator: "In"
      values: ["proxmox"]

patches:
  - |
    machine:
      install:
        disk: /dev/sda
      kubelet:
        nodeIP:
          validSubnets:
            - 0.0.0.0/0
        extraArgs:
          rotate-server-certificates: "true"
      network:
        interfaces:
          - interface: eth0
            dhcp: true
      time:
        servers:
          - time.cloudflare.com
          - time.google.com

---
# Resource requirements for Terraform
# These values should match your terraform.tfvars configuration

# Node specifications:
# - Control Planes: 1
# - Workers: 3
# - Total Nodes: 4
#
# Per-node resources:
# - CPU: 2 cores
# - Memory: 4096 MB
# - Disk: 100 GB
#
# Total resources:
# - CPU: 8 cores
# - Memory: 16384 MB (16 GB)
# - Disk: 400 GB

# Update terraform/vsphere/terraform.tfvars.dk1d:
#   node_count     = 4
#   node_cpu       = 2
#   node_memory    = 4096
#   node_disk_size = 100
