variable "proxmox_endpoint" {
  description = "Proxmox API endpoint"
  type        = string
}

variable "proxmox_username" {
  description = "Proxmox username (e.g., root@pam) - used with password auth"
  type        = string
  default     = ""
  sensitive   = true
}

variable "proxmox_password" {
  description = "Proxmox password - used with username/password auth"
  type        = string
  default     = ""
  sensitive   = true
}

variable "proxmox_api_token" {
  description = "Proxmox API token (recommended) - format: USER@REALM!TOKENID=UUID"
  type        = string
  default     = ""
  sensitive   = true
}

variable "proxmox_insecure" {
  description = "Allow insecure SSL connections"
  type        = bool
  default     = false
}

variable "proxmox_node" {
  description = "Proxmox node name"
  type        = string
}

variable "proxmox_datastore" {
  description = "Proxmox datastore for VM disks"
  type        = string
  default     = "local-lvm"
}

variable "proxmox_iso_storage" {
  description = "Proxmox storage for ISO files (must be file-based, e.g., local)"
  type        = string
  default     = "local"
}

variable "proxmox_bridge" {
  description = "Proxmox network bridge"
  type        = string
  default     = "vmbr0"
}

variable "proxmox_ssh_username" {
  description = "SSH username for Proxmox host (e.g., root)"
  type        = string
  default     = "root"
}

variable "proxmox_ssh_private_key_file" {
  description = "Path to SSH private key file for Proxmox host"
  type        = string
  default     = ""
}

variable "proxmox_ssh_private_key" {
  description = "SSH private key content for Proxmox host authentication (leave empty to use proxmox_ssh_private_key_file)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "talos_version" {
  description = "Talos version (informational only - actual version determined by Omni ISO)"
  type        = string
  default     = "1.9.0"
}

variable "omni_iso_name" {
  description = "Name of Omni ISO in Proxmox storage (generated by prepare-omni-iso.sh)"
  type        = string
}

variable "cluster_name" {
  description = "Name of the Talos cluster (used for VM naming prefix)"
  type        = string
}

variable "vm_id_start" {
  description = "Starting VM ID for Proxmox"
  type        = number
  default     = 8000
}

# Multi-VM configuration (required)
variable "vm_configs" {
  description = "List of VM configurations. Each config specifies count, cpu, memory, disk, and role."
  type = list(object({
    count  = number
    cpu    = number
    memory = number
    disk   = number
    role   = string # "controlplane" or "worker" or any descriptive name
  }))
  
  validation {
    condition     = length(var.vm_configs) > 0
    error_message = "At least one VM configuration is required."
  }
  
  validation {
    condition     = alltrue([for config in var.vm_configs : config.count > 0])
    error_message = "All VM configurations must have count > 0."
  }
}
